// Generated by CoffeeScript 1.8.0
(function() {
  var Logger;

  Logger = require('./index');

  exports.init = function(test) {
    var logger;
    logger = new Logger.Logger();
    logger.log('lalalla', {
      bla: 3
    }, 'sag', 'sdgsag');
    return test.done();
  };

  exports.console = function(test) {
    var logger;
    logger = new Logger.Logger();
    logger.outputs.push(new Logger.Console());
    logger.log('lalalla', {
      bla: 3
    }, 'sag', 'sdgsag');
    return test.done();
  };

  exports.udp = function(test) {
    var logger;
    logger = new Logger.Logger();
    logger.outputs.push(new Logger.Udp());
    logger.log('lalalla', {
      bla: 3
    }, 'sag', 'sdgsag');
    return test.done();
  };

}).call(this);
